#!/bin/bash

cd /tmp/
wget http://www.cs.rutgers.edu/~zhewang/anti-ddos.rb
apt-get update
cd /tmp/anti-ddos-setup/
$PWD/prep-trema
#$PWD/ovs-init
$PWD/ovs-start

/usr/local/bin/rubydir/bin/ruby $PWD/find-interfaces.rb 192.168.128.1 192.168.129.1 192.168.130.1 | while read iface; do
    ifconfig $iface 0
    ovs-vsctl add-port br0 $iface < /dev/null
done
